name: refresh

on:
  push:
    branches:
      - refresh
    
env:
  DBT_PROFILES_DIR: ./

jobs:
  refresh:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: read
      packages: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@master

      - name: DuckDB setup
        uses: opt-nc/setup-duckdb-action@main

      - uses: actions/setup-python@master

      - name: Lint with sqlfluff
        run: |
          pip install sqlfluff
          sqlfluff lint -r L020,L021,L049 --dialect ansi -v models/
    
          # Linting only modified models
          # git fetch origin main:main
          # git diff main --name-only --diff-filter=d | egrep '^models/.*sql$$' | xargs -r sqlfluff lint

      - name: Install dependencies
        run: |
          pip install dbt-duckdb
          dbt deps 

      - name: Run dbt source freshness
        run: dbt source freshness

      - name: Run dbt build
        id: run_dbt_build
        run: dbt build --select result:error+ source_status:fresher+ --defer --state docs
        continue-on-error: true

      - name: Full dbt build 
        if: steps.run_dbt_build.outcome != 'success'
        run: dbt build

      - name: Run docs generate
        run: dbt docs generate

      - name: Generate dbt docs
        run: |
          mkdir -p ${{ github.workspace }}/docs && cp ${{ github.workspace }}/target/*.json github.workspace }}/docs
          cp ${{ github.workspace }}/target/*.html github.workspace }}/docs
          cp ${{ github.workspace }}/target/*.gpickle github.workspace }}/docs

      - run: ls -l ${{ github.workspace }}/docs

      - run: git status

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add --all :/
          git commit -m "Add docs"
        continue-on-error: true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
        continue-on-error: true
