# https://github.com/AnimMouse/setup-rclone
name: scheduled

on:
  push:
    branches:
      - develop

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
        
      - name: Add Rclone service account file
        uses: AnimMouse/setup-rclone/service-account-file@v1
        with:
          service_account_filename: service-account-file.json
          service_account_file: ${{ secrets.SERVICE_ACCOUNT_FILE }}
        
      - run: rclone copy sm2drive:Vzduchotechnika/Latest/2.csv ./

      - name: Print Number of the SM House
        run: |
          vzt=$(head -n 1 ./2.csv | grep "Date" | grep -Eo 'vzt[0-9]{2}_temp-tea-sani' | grep -Eo '[0-9]{2}')
          echo "Number of the SM House: $vzt"

      - name: Print date 
        run: |
          date=$(tail ./2.csv | grep "00:00" | tail -n 1 | grep -Eo '[0-9]{2}.[0-9]{2}.[0-9]{4} [0-9]{2}:[0-9]{2}:[0-9]{2}')
          echo "Date: $date"