# https://github.com/AnimMouse/setup-rclone
name: scheduled

on:
  push:
    branches:
      - develop

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
        
      - name: Add Rclone service account file
        uses: AnimMouse/setup-rclone/service-account-file@v1
        with:
          service_account_filename: service-account-file.json
          service_account_file: ${{ secrets.SERVICE_ACCOUNT_FILE }}
        
      - run: rclone copy sm2drive:Vzduchotechnika/Latest/2.csv ./

      - name: Check first line of the file
        run: |
          first_line=$(head -n 1 ./2.csv)
          if [[ "$first_line" == *"VZT 02"* ]]; then
            echo "String 'VZT 02' found in the first line."
          else
            echo "String 'VZT 02' not found in the first line."
            exit 1
          fi