version: 2

sources:
  - name: csv_google
    tables:
      - name: fact_original
        config:
          external_location: "read_csv('./gdrive/fact.csv')"

  - name: duckdb
    schema: main  
    tables:
      - name: sm2_01
      - name: sm2_02
      - name: sm2_03
      - name: sm2_04
      - name: sm2_05
      - name: sm2_06
      - name: sm2_07
      - name: sm2_08
      - name: sm2_09

models:
  - name: fact
    description: the fact table
    columns:
      - name: time
        description: This is a date time
        tests:
          - not_null
